CREATE USER EMPLOYEE_APP IDENTIFIED BY change_me;

GRANT CONNECT, RESOURCE TO EMPLOYEE_APP;
GRANT CREATE SESSION TO EMPLOYEE_APP;
GRANT CREATE TABLE TO EMPLOYEE_APP;
GRANT CREATE SEQUENCE TO EMPLOYEE_APP;
GRANT CREATE PROCEDURE TO EMPLOYEE_APP;
GRANT UNLIMITED TABLESPACE TO EMPLOYEE_APP;
