CREATE TABLE EMPLOYEES (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    EMPLOYEE_ID VARCHAR2(255) NOT NULL UNIQUE,
    EMPLOYEE_ROLE VARCHAR2(255) NOT NULL,
    EMAIL_ADDRESS VARCHAR2(255) NOT NULL UNIQUE,
    PHONE_NUMBER VARCHAR2(255) NOT NULL
);

CREATE OR REPLACE PROCEDURE SAVE_EMPLOYEE (
    p_employee_id   IN VARCHAR2,
    p_name          IN VARCHAR2,
    p_employee_role IN VARCHAR2,
    p_email_address IN VARCHAR2,
    p_phone_number  IN VARCHAR2
)
AS
BEGIN
    MERGE INTO EMPLOYEES e
    USING (
        SELECT p_employee_id AS employee_id FROM dual
    ) src
    ON (e.employee_id = src.employee_id)
    WHEN MATCHED THEN
        UPDATE SET
            e.name = p_name,
            e.employee_role = p_employee_role,
            e.email_address = p_email_address,
            e.phone_number = p_phone_number
    WHEN NOT MATCHED THEN
        INSERT (
            employee_id,
            name,
            employee_role,
            email_address,
            phone_number
        )
        VALUES (
            p_employee_id,
            p_name,
            p_employee_role,
            p_email_address,
            p_phone_number
        );
END;
/
