spring.application.name=EmployerServiceApplication

spring.datasource.url=jdbc:oracle:thin:@192.168.1.210:1521/FREEPDB1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=EMPLOYEE_APP
spring.datasource.password=change_me

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=false

external.employee-api.url=https://localhost:8080/api/employees
